#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=4
#SBATCH --job-name=pipe
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=72
#SBATCH --time=30:05:00
#SBATCH --output=outputs/pinn(500x500)/slurm_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

# Activate your environment
source activate myenv

# Your job starts in the directory where you call sbatch

# set variables
cd #path to scripts

# run script
srun python -u 500-pinn-82.py