#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=4
#SBATCH --job-name=pipe
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=72
#SBATCH --time=05:05:00
#SBATCH --output=outputs/pinn(250x250)/slurm_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

# Activate your environment
source activate myenv

# Your job starts in the directory where you call sbatch

# set variables
DATA_PATH=$TMPDIR

# run script
srun python -u pinn_500x500.py